<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VariantAttributesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('variant_attributes')->delete();
        
        \DB::table('variant_attributes')->insert(array (
            0 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 1,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9377,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            1 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 2,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            2 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 3,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '914578541121',
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            3 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 4,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '42400-28154-37',
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            4 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 5,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'SUPER_HERO',
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            5 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 6,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9615,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            6 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 7,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Windsurf sail : variant dependent price',
                'variant_id' => 1,
            ),
            7 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 8,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://cdn.boards-and-more.com/system/product_picture_gallery_pictures/files/6493/5a1d/2648/b000/cc96/391c/original/DTW24_SuperHERO_Rendering_C-01_Screen_72.png',
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            8 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 9,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 742.56,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            9 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 10,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 989.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            10 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 11,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 4.8,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            11 => 
            array (
                'attribute_id' => 21,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 12,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 3.7,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 1,
            ),
            12 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 13,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9377,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            13 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 14,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            14 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 15,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '914578541122',
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            15 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 16,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '42400-28154-42',
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            16 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 17,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'SUPER_HERO',
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            17 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 18,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9615,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            18 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 19,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Windsurf sail : variant dependent price',
                'variant_id' => 2,
            ),
            19 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 20,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://cdn.boards-and-more.com/system/product_picture_gallery_pictures/files/6493/5a1d/2648/b000/cc96/391c/original/DTW24_SuperHERO_Rendering_C-01_Screen_72.png',
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            20 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 21,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 752.56,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            21 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 22,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1005.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            22 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 23,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 4.9,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            23 => 
            array (
                'attribute_id' => 21,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 24,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 4.2,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 2,
            ),
            24 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 25,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9377,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            25 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 26,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            26 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 27,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '914578541123',
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            27 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 28,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '42400-28154-47',
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            28 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 29,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'SUPER_HERO',
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            29 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 30,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9615,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            30 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 31,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Windsurf sail : variant dependent price',
                'variant_id' => 3,
            ),
            31 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 32,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://cdn.boards-and-more.com/system/product_picture_gallery_pictures/files/6493/5a1d/2648/b000/cc96/391c/original/DTW24_SuperHERO_Rendering_C-01_Screen_72.png',
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            32 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 33,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 762.56,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            33 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 34,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1105.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            34 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 35,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            35 => 
            array (
                'attribute_id' => 21,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 36,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 4.7,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 3,
            ),
            36 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 37,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9377,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            37 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 38,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            38 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 39,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '914578541124',
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            39 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 40,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '42400-28154-50',
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            40 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 41,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'SUPER_HERO',
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            41 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 42,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9615,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            42 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 43,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Windsurf sail : variant dependent price',
                'variant_id' => 4,
            ),
            43 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 44,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://cdn.boards-and-more.com/system/product_picture_gallery_pictures/files/6493/5a1d/2648/b000/cc96/391c/original/DTW24_SuperHERO_Rendering_C-01_Screen_72.png',
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            44 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 45,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 782.56,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            45 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 46,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1205.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            46 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 47,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            47 => 
            array (
                'attribute_id' => 21,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 48,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 4,
            ),
            48 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 49,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9404,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            49 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 50,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '814578545487',
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            50 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 51,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '77244-0103-52',
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            51 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 52,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MITU PRO CARBON',
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            52 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 53,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9646,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            53 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 54,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Kite surf board : variant independant price',
                'variant_id' => 5,
            ),
            54 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 55,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://fr.f-one.world/app/uploads/2023/08/mitu-pro-carbon-4-1280x1280.png',
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            55 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 56,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 890.12,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            56 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 57,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1699.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            57 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 58,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.4,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            58 => 
            array (
                'attribute_id' => 24,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 59,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '5\'2',
                'value_txt' => NULL,
                'variant_id' => 5,
            ),
            59 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 60,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9404,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            60 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 61,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '814578545488',
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            61 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 62,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '77244-0103-54',
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            62 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 63,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MITU PRO CARBON',
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            63 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 64,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9646,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            64 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 65,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Kite surf board : variant independant price',
                'variant_id' => 6,
            ),
            65 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 66,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://fr.f-one.world/app/uploads/2023/08/mitu-pro-carbon-4-1280x1280.png',
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            66 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 67,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 890.12,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            67 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 68,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1699.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            68 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 69,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.4,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            69 => 
            array (
                'attribute_id' => 24,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 70,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '5\'4',
                'value_txt' => NULL,
                'variant_id' => 6,
            ),
            70 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 71,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9404,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            71 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 72,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '814578545489',
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            72 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 73,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '77244-0103-56',
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            73 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 74,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MITU PRO CARBON',
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            74 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 75,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9646,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            75 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 76,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Kite surf board : variant independant price',
                'variant_id' => 7,
            ),
            76 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 77,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://fr.f-one.world/app/uploads/2023/08/mitu-pro-carbon-4-1280x1280.png',
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            77 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 78,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 890.12,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            78 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 79,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1699.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            79 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 80,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.4,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            80 => 
            array (
                'attribute_id' => 24,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 81,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '5\'6',
                'value_txt' => NULL,
                'variant_id' => 7,
            ),
            81 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 82,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9404,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            82 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 83,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '814578545410',
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            83 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 84,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '77244-0103-58',
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            84 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 85,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MITU PRO CARBON',
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            85 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 86,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9646,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            86 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 87,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Kite surf board : variant independant price',
                'variant_id' => 8,
            ),
            87 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 88,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://fr.f-one.world/app/uploads/2023/08/mitu-pro-carbon-4-1280x1280.png',
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            88 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 89,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 890.12,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            89 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 90,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 1699.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            90 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 91,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 5.4,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            91 => 
            array (
                'attribute_id' => 24,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 92,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '5\'8',
                'value_txt' => NULL,
                'variant_id' => 8,
            ),
            92 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 93,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            93 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 94,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            94 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 95,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589754',
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            95 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 96,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_D_01_S',
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            96 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 97,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            97 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 98,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            98 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 99,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 9,
            ),
            99 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 100,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dw311e7a10/images/recadre/MVT457_D_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            100 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 101,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            101 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 102,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            102 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 103,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            103 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 104,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 395,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            104 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 105,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 7047,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 9,
            ),
            105 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 106,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            106 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 107,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            107 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 108,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589755',
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            108 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 109,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_D_01_M',
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            109 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 110,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            110 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 111,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            111 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 112,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 10,
            ),
            112 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 113,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dw311e7a10/images/recadre/MVT457_D_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            113 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 114,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            114 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 115,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            115 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 116,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            116 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 117,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 398,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            117 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 118,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 7047,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 10,
            ),
            118 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 119,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            119 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 120,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            120 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 121,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589756',
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            121 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 122,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_D_01_L',
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            122 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 123,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            123 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 124,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            124 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 125,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 11,
            ),
            125 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 126,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dw311e7a10/images/recadre/MVT457_D_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            126 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 127,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            127 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 128,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            128 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 129,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            129 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 130,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 401,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            130 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 131,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 7047,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 11,
            ),
            131 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 132,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            132 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 133,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            133 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 134,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589757',
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            134 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 135,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_D_01_XL',
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            135 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 136,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            136 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 137,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            137 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 138,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 12,
            ),
            138 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 139,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dw311e7a10/images/recadre/MVT457_D_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            139 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 140,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            140 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 141,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            141 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 142,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            142 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 143,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 403,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            143 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 144,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 7047,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 12,
            ),
            144 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 145,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            145 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 146,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            146 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 147,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589764',
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            147 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 148,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_C_01_S',
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            148 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 149,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            149 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 150,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            150 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 151,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 13,
            ),
            151 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 152,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dwa458390e/images/recadre/MVT457_C_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            152 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 153,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            153 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 154,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            154 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 155,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            155 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 156,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 395,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            156 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 157,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 8286,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 13,
            ),
            157 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 158,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            158 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 159,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            159 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 160,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589765',
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            160 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 161,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_C_01_S',
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            161 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 162,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            162 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 163,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            163 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 164,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 14,
            ),
            164 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 165,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dwa458390e/images/recadre/MVT457_C_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            165 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 166,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            166 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 167,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            167 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 168,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            168 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 169,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 398,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            169 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 170,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 8286,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 14,
            ),
            170 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 171,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            171 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 172,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            172 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 173,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589766',
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            173 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 174,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_C_01_S',
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            174 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 175,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            175 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 176,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            176 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 177,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 15,
            ),
            177 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 178,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dwa458390e/images/recadre/MVT457_C_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            178 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 179,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            179 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 180,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            180 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 181,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            181 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 182,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 401,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            182 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 183,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 8286,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 15,
            ),
            183 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 184,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9510,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            184 => 
            array (
                'attribute_id' => 2,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 185,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 2024,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            185 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 186,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '714578589767',
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            186 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 187,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'MVT457_C_01_S',
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            187 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 188,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'NAIKOON JKT',
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            188 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 189,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9796,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            189 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 190,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
            'value_txt' => 'Snowboard Jkt: double variant index (color + size)',
                'variant_id' => 16,
            ),
            190 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 191,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'https://www.picture-organic-clothing.com/dw/image/v2/BGFP_PRD/on/demandware.static/-/Sites-poc-master-catalog/default/dwa458390e/images/recadre/MVT457_C_01.jpg',
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            191 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 192,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 190.42,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            192 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 193,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 400.0,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            193 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 194,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 2.1,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            194 => 
            array (
                'attribute_id' => 37,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 195,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 403,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            195 => 
            array (
                'attribute_id' => 33,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 196,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 8286,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 16,
            ),
            196 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 197,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9593,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            197 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 198,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '57884211454',
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            198 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 199,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '011051',
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            199 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 200,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'Outils pour chants Pro',
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            200 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 201,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9715,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            201 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 202,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Ski maintenance tool : no variant product',
                'variant_id' => 17,
            ),
            202 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 203,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'http://img.vola.fr/articles/9a1fbe1a78b74854e8d9c82164e28512b2a765f3.png_750x608_max.png',
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            203 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 204,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 52.56,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            204 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 205,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 89.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            205 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 206,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 0.12,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 17,
            ),
            206 => 
            array (
                'attribute_id' => 1,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 207,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9593,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            207 => 
            array (
                'attribute_id' => 3,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 208,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '57884211455',
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            208 => 
            array (
                'attribute_id' => 4,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 209,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => '011132',
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            209 => 
            array (
                'attribute_id' => 5,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 210,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'Edgerazor',
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            210 => 
            array (
                'attribute_id' => 6,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 211,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => 9715,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            211 => 
            array (
                'attribute_id' => 7,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 212,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => 'Ski maintenance tool : no variant product',
                'variant_id' => 18,
            ),
            212 => 
            array (
                'attribute_id' => 9,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 213,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => NULL,
                'value_int' => NULL,
                'value_str' => 'http://img.vola.fr/articles/5c87372aa070909c9412c968520cf1ea2fd13b5c.png_750x608_max.png',
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            213 => 
            array (
                'attribute_id' => 10,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 214,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 32.56,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            214 => 
            array (
                'attribute_id' => 11,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 215,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 59.99,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
            215 => 
            array (
                'attribute_id' => 12,
                'created_at' => '2023-10-05 22:22:51',
                'id' => 216,
                'updated_at' => '2023-10-05 22:22:51',
                'value_float' => 0.12,
                'value_int' => NULL,
                'value_str' => NULL,
                'value_txt' => NULL,
                'variant_id' => 18,
            ),
        ));
        
        
    }
}